/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationmedecin;

import EJB.EJBAnalysesRemote;
import EJB.EJBPatientRemote;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.jms.Connection;
import javax.jms.ConnectionFactory;
import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.MessageListener;
import javax.jms.Session;
import javax.jms.TextMessage;
import javax.jms.Topic;

/**
 *
 * @author tibha
 */
public class Medecin extends javax.swing.JFrame implements MessageListener {

    @Resource(mappedName = "jms/myTopic")
    private static Topic myTopic;

    @Resource(mappedName = "jms/myTopicFactory")
    private static ConnectionFactory myTopicFactory;

    @EJB
    private static EJBPatientRemote eJBPatient;

    @EJB
    private static EJBAnalysesRemote eJBAnalyses;

    /**
     * Creates new form Medecin
     */
    
    private static Connection connection = null;
    private static Session session = null;
    private static MessageConsumer consumer;
    public Medecin() {
        try {
            initComponents();
            
            connection = myTopicFactory.createConnection();
            session = connection.createSession(false,Session.AUTO_ACKNOWLEDGE);
            connection.start();
            consumer = session.createConsumer(myTopic);
            
            consumer.setMessageListener(this);
            if(eJBPatient.CheckIdMedecin())
                System.out.println("Connexion OK");
            else
            {
                exit(0);
            }            
            System.out.println(eJBPatient.sayHello("Jean-claude Van Damme"));
            System.out.println(eJBAnalyses.sayHello("Jean-claude Van Damme"));
            System.out.println("Patient : " + eJBPatient.getPatient(2));
        } catch (JMSException ex) {
            Logger.getLogger(Medecin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medecin().setVisible(true);
            }
        });
    }
    @Override
    public void onMessage(Message message) {
        try
        {
            TextMessage tm = (TextMessage)message;
            
            System.out.println("Message = " + tm.getText());
        } catch (JMSException ex) {
            Logger.getLogger(Medecin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
